# Generated by Django 2.1.8 on 2019-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhaar_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('year_of_birth', models.CharField(max_length=264)),
                ('gender', models.CharField(max_length=264)),
                ('Aadhaar_num', models.IntegerField()),
                ('Aadhaar_Image', models.ImageField(upload_to='Aadhaar_images/')),
            ],
        ),
    ]
