# Generated by Django 2.1.8 on 2019-10-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aadhaar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaar_detail',
            name='image_name',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AlterField(
            model_name='aadhaar_detail',
            name='Aadhaar_num',
            field=models.IntegerField(default=0),
        ),
    ]
