# Generated by Django 2.1.8 on 2019-10-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aadhaar_app', '0002_auto_20191015_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaar_detail',
            name='gender',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaar_detail',
            name='name',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaar_detail',
            name='year_of_birth',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
